name: build
on:
  push:
    branches:
      - "dev"
      - "main"
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    uses: ditkrg/build-image-workflow/.github/workflows/workflow.yaml@v1
    with:
      image: common/meilisync
    secrets:
      username: ${{ secrets.HARBOR_USER }}
      password: ${{ secrets.HARBOR_TOKEN }}

      # test dev
